name: arcface
channels:
    - pytorch
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - numpy
    - pandas
    - pytorch
    - torchvision
    - scikit-learn
    - tqdm
    - opencv
    - albumentations
    - mtcnn
    - tensorflow==2.15.0
    - grad-cam